### ISSUE TITLE
Stage "refreshed" theme version on NEXT

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-theme-hpe#308]
## Tasks

- [ ] Finalize any theme adjustments/tweaks
- [ ] Incorporate changes into NEXT branch
- [x] Update dependencies

## Acceptance Criteria

- [ ] grommet updated to accommodate any theme requirements, release grommet in conjunction with publishing the theme (next)
- [ ] Have all "Brand refresh" theme changes merged on NEXT branch
- [ ] Update Design System site package.json to point to NEXT-stable

**Comment by taysea** [comment]
Friday 2/3/23:
- Grommet PRs related to theme enhancements have been merged.

Next steps:
- Apply the enhancements to NEXT stable branch. Expecting I'll have that done by EOD Monday.

**Comment by taysea** [comment]
There are a few remaining items to iron out:
- [ ] Icon sizing --> should we adjust sizing to align with font-size as opposed to line height?
- [ ] Finalize tab design: https://github.com/grommet/hpe-design-system/issues/3107
- [ ] Anchor size at medium (18px) doesn't meet AA color contrast (upping to 14pt seems to be the minimum, which is 18.667px). We might also explore the 900 font weight.
- [ ] Add new button kind for what Chris has as "Toolbar" and ideate on naming
- [ ] Determine name for what we're calling "HPE Web" theme (larger typescale for .COM). This is a bit misleading since all things we are building exist on the web, some are product and some are .COM/Marketing.

**Comment by taysea** [comment]
Next steps:
- https://github.com/grommet/grommet-theme-hpe/issues/318
- https://github.com/grommet/grommet-theme-hpe/issues/319

**Comment by taysea** [comment]
This PR captures the current state of the changes and "notes" for consideration: https://github.com/grommet/grommet-theme-hpe/pull/310

**Comment by taysea** [comment]
Open items:
- [ ] Safari icon-only bug
- [ ] Change of icon large size is a big jump from prior value, causing issues in Stack example --> breaking change to call out
- [ ] Finalize migration guide wording, update the screenshots with latest styles
- [ ] Grommet Notification icon height adjustment
